apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-k6nf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-k6nf
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-k6nf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-k6nf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-k6nf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ealy-tenant/status-quarkus-io/statusquarkusio-k6nf@sha256:9eed80fa69c9f7f92ed6726259356462be32e822db4a18e338f92f755095cc59
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
